### ISSUE TITLE
Installation / Display

### ISSUE THREAD

**Issue by shrimp69** [siddii/angular-feeds#22]
I was able to install the angular-feeds component. But I'm really unsure how to actually display it on the mirror?

**Comment by siddii** [comment]
Please have a look at this app - http://siddii.github.io/angular-feeds/app/

Any of the sample code should help you get started...

<feed summary="true" url="http://stackoverflow.com/feeds/tag?tagnames=angularjs&sort=newest" count="5"/>

**Comment by shrimp69** [comment]
Thanka for your fast reponse. I actually tried the sample code but it doesnt do anything ( at least not visibly )

**Comment by siddii** [comment]
Is the angular-feed module included in your project?

**Comment by siddii** [comment]
Something like this... 
```
angular.module('feeds-demo', [
    'feeds',
    'ngSanitize'
  ])

```

**Comment by shrimp69** [comment]
I dont think so actually! Ive been looking all over the place to find the file which managea the module loader..

I installed it
I included it in the index.html like the other bower components

**Comment by siddii** [comment]
OK, here is a simple plunkr showing how this module works - https://plnkr.co/edit/LS0uWdDPBv78KRLjJEdu?p=preview

**Comment by shrimp69** [comment]
Thank you for your usefull pnkr script! I looked at it in my browser and I thought I understood what it does. I then tried to add exactly this to my mirror's index.html but it only displays the hard coded <h2>Feed</h2> and nothing else. It doesnt seem to load the script/do anything with it. Do you have an idea why?
