### ISSUE TITLE
Mixed Content - This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by tdharris** [siddii/angular-feeds#31]
SSL only isn't working yet as far as I can tell. Please check out even the demo site with `https`:
https://siddii.github.io/angular-feeds/app/

The above has the same problem I was experiencing at the end of issue #25.

**Comment by tdharris** [comment]
If the demo site is ever fixed with `https`, please let us know how we can do the same:
https://siddii.github.io/angular-feeds/app/
_Note: You'll see the widgets never load._

These are the related `js` dependencies being brought in:
```
yui/build/yui/yui-min.js
yui/build/oop/oop-min.js
yui/build/jsonp/jsonp-min.js
yui/build/jsonp-url/jsonp-url-min.js
yui/build/yql/yql-min.js
yui/build/yql-jsonp/yql-jsonp-min.js
angular-feeds/app/angular-feeds/angular-feeds.js
```

**Comment by tdharris** [comment]
YUI supports `https` for the call to `http://query.yahooapis.com/v1/public/yql?q=`. The following code replacement should work for `angular-feeds.js`:
```
function performYQLQuery (feedURL) {
    return function (Y) {
        var query = 'select * from feed(0,' + count + ') where url = "' + feedURL + '"',
            opts = ('https:' == document.location.protocol ? { proto: 'https' } : {}); // default is http
        
        Y.YQL(query, parseYQLResponse, {}, opts);
    }
}
```

However, I was about to fork and fix, but it looks like this type of logic already exists in some other angular-feeds.js file from this repository. I suspect the wrong dependency was being loaded in (same for public demo site) and/or the bower dependency wasn't getting the updated code.

I fixed by pulling in the file manually from this repo and skipping any bower stuffs:
`wget https://raw.githubusercontent.com/siddii/angular-feeds/master/app/angular-feeds/angular-feeds.min.js`

Then it worked. I recommend the demo site "Getting Started" guide be updated, verify the bower version of the repo is current and fix to have consistent `angular-feeds.js` across the repo.

**Comment by siddii** [comment]
Fixed now
