### ISSUE TITLE
Is this still functional?

### ISSUE THREAD

**Issue by aktary** [siddii/angular-feeds#4]
Every RSS url I put in gives a 400 error with the message "The specified feed URL is invalid".  This is a pretty simple module to implement, so I don't think I've done anything wrong... and I've validated that the URLs are good with the "Feed Tester".  Did the Google Feeds API get shut down or something?

**Comment by siddii** [comment]
Yes, it is functional. All the feeds on this page http://siddii.github.io/angular-feeds/app/ is rendered through this module?

What is the feed url you are having problem with?

**Comment by aktary** [comment]
http://www.hugeinc.com/news/rss

**Comment by siddii** [comment]
I just ran it on feed tester & it's working fine for me. Are you behind a
firewall where the Google feeds url is being blocked?

**Comment by aktary** [comment]
you ran it locally?  It worked for me on the "Feed Tester", but not locally
on my machine, nor on my server.  No, I'm not behind a firewall.

**Comment by siddii** [comment]
This plnkr is working for me.

http://plnkr.co/edit/LS0uWdDPBv78KRLjJEdu?p=preview
