### ISSUE TITLE
Unnecessary console.log

### ISSUE THREAD

**Issue by RyanMilstead1** [siddii/angular-feeds#8]
Really great work. Used this directive really easily and it's also easy to customize.

I'm just wondering if it's necessary / expected to console log all of the articles once the feed loads? It's not causing any issues for my app, it's just distracting when I'm developing.

Really easy fix, just wondering if that was the intended behavior?

Thanks!

**Comment by siddii** [comment]
Thanks for reporting. It's removed from the master a while ago. I guess, the `dist` scripts & other branches haven't been synced up properly.

**Comment by RyanMilstead1** [comment]
No worries. Glad I could help!

**Comment by bropp** [comment]
Ran into the same issue, looks like the commit to remove it from the source didn't update the minified/dist versions. Anyway we could get that removed? Willing to submit a pull request if given instruction as to how to recreate the files.

Thanks!

**Comment by siddii** [comment]
Fixed in v0.0.4
